config/routes.rb
Rails.application.routes.draw do
  root 'sessions#welcome'
  get '/signup', to: 'gamers#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback' => 'sessions#omniauth'
  get '/home', to: 'gamers#home'
  resources :gatherings
  resources :groups do
    resources :gatherings
  end
  resources :gamers, except: [:show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gamer.rb
class Gamer < ApplicationRecord
    has_secure_password
    has_many :gatherings
    has_many :groups, through: :gatherings
    validates :username, uniqueness: true, presence: true

    def self.from_omniauth(auth)
        where(username: auth.info.email).first_or_initialize do |gamer|
            gamer.username = auth.info.email
            gamer.password = SecureRandom.hex
        end
    end
end

app/models/gathering.rb
class Gathering < ApplicationRecord
  belongs_to :gamer
  belongs_to :group
  validates :game_cafe, presence: true
  validates :day_of_week, presence: true
  validates :group_id, presence: true
  accepts_nested_attributes_for :group, reject_if: :all_blank
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :gatherings
    has_many :gamers, through: :gatherings
    validates :game_title, uniqueness: true, presence: true
    validates :game_category, presence: true

    def self.board_games(params)
        where(game_category: 'Board Game')
    end

    def self.card_games(params)
        where(game_category: 'Card Game')
    end

    def self.rpg(params)
        where(game_category: 'RPG')
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?, :require_login
    
    private

    def current_user
        @current_user ||= Gamer.find_by_id(session[:gamer_id])
    end

    def logged_in?
        !!current_user
    end
  
    def require_login
        if !logged_in?
            redirect_to root_path
        end
    end
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController

    def new
        @gamer = Gamer.new
    end

    def create
        @gamer = Gamer.new(gamer_params)
        if @gamer.save
            session[:gamer_id] = @gamer.id
            redirect_to home_path
        else
            render :new
        end
    end
    
    def home
        @gamer = current_user
    end

    private

    def gamer_params
        params.require(:gamer).permit(:username, :password)
    end
end

app/controllers/gatherings_controller.rb
class GatheringsController < ApplicationController
    before_action :require_login
    before_action :set_gathering, only: [:show, :edit, :update, :destroy]
    before_action :allow_changes, only: [:update, :destroy]

    def index
        if params[:group_id]
            @gatherings = Group.find_by_id(params[:group_id]).gatherings
        else
            @gatherings = Gathering.order(:gamer_id)
        end
    end

    def new
        @group = Group.find_by_id(params[:group_id]) if params[:group_id]
        @gathering = Gathering.new
    end

    def create
        @gathering = current_user.gatherings.new(gathering_params)
        if @gathering.save
            redirect_to gathering_path(@gathering)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @gathering.update(gathering_params)
            redirect_to gathering_path(@gathering)
        else
            render :edit
        end
    end

    def destroy
        @gathering.destroy
        redirect_to gatherings_path
    end

    private

    def gathering_params
        params.require(:gathering).permit(:game_cafe, :day_of_week, :gamer_id,
        :group_id, group_attributes: [:game_title, :game_category])
    end

    def require_login
        return head(:forbidden) unless session.include? :gamer_id
    end

    def set_gathering
        @gathering = Gathering.find_by_id(params[:id])
        return head(:not_found) unless @gathering
    end

    def allow_changes
        return head(:forbidden) unless @gathering.gamer_id == current_user
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :require_login
    before_action :set_group, only: [:show, :edit, :update, :destroy]
    before_action :allow_changes, only: [:update, :destroy]

    def index
        @groups = Group.order(:game_title)
        @groups = @groups.rpg(params[:game_category]['RPG']) if params[:game_category] && params[:game_category]['RPG']
        @groups = @groups.board_games(params[:game_category]['Board Game']) if params[:game_category] && params[:game_category]['Board Game']
        @groups = @groups.card_games(params[:game_category]['Card Game']) if params[:game_category] && params[:game_category]['Card Game']
    end
    
    def new
        @group = Group.new
    end

    def create
        @group = Group.new(group_params)
        if @group.save
            redirect_to group_path(@group)
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @group.update(group_params)
            redirect_to group_path(@group)
        else
            render :edit
        end
    end

    def destroy
        @group.destroy
        redirect_to groups_path
    end

    private

    def group_params
        params.require(:group).permit(:game_title, :game_category)
    end

    def require_login
        return head(:forbidden) unless session.include? :gamer_id
    end

    def set_group
        @group = Group.find_by_id(params[:id])
        return head(:not_found) unless @group
    end

    def allow_changes
        return head(:forbidden) unless @gathering.gamer_id == current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def welcome
  end
  
  def new
  end

  def create
    @gamer = Gamer.find_by(username: params[:gamer][:username])
    if @gamer && @gamer.authenticate(params[:gamer][:password])
      login_and_redirect
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def omniauth
    @gamer = Gamer.from_omniauth(auth)
    @gamer.save
    login_and_redirect
  end

  private

  def auth
    request.env['omniauth.auth']
  end

  def login_and_redirect
    session[:gamer_id] = @gamer.id
    redirect_to home_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gamers_helper.rb
module GamersHelper
end

app/helpers/gatherings_helper.rb
module GatheringsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/gamers/_form.html.erb
<%= form_for(@gamer) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit 'Register' %>
<% end %>

app/views/gamers/home.html.erb
<h1>List of my current gaming groups:</h1>

<ol>
<% @gamer.groups.each do |group| %>
    <li><%= link_to group.game_title, group_path(group) %></li>
<% end %>
</ol>

<%= link_to 'Create New Gaming Group', new_group_path %>
<br><br>
<%= link_to 'Create a New Gathering', new_gathering_path %>
<br><br>
<%= link_to 'List of Gaming Groups', groups_path %>
<br><br>
<%= link_to 'View All Gatherings', gatherings_path %>

app/views/gamers/new.html.erb
<h1>Register</h1>

<%= render partial: 'layouts/errors', locals: {object: @gamer} %>

<%= render 'form' %>

app/views/gamers/show.html.erb
<h1>List of my current gaming group gatherings:</h1>

<ol>
<% @gamer.gatherings.each do |g| %>
    <li><%= g.group.game_title %> meets at <%= g.game_cafe %> on <%= g.day_of_week %>.</li>
<% end %>
</ol>

<%= link_to 'Create New Gaming Group', new_group_path %>
<br><br>
<%= link_to 'Create a New Gathering', new_gathering_path %>
<br><br>
<%= link_to 'Join a Gaming Group', groups_path %>
<br><br>
<%= link_to 'Join a Gaming Group Gathering', gatherings_path %>

app/views/gatherings/_form.html.erb
<%= f.label :game_cafe, 'Which Cafe?' %>
    <%= f.select :game_cafe, [
        ['Vigilante', 'Vigilante'], 
        ['Emerald Tavern', 'Emerald Tavern'], 
        ['Dragons Lair', 'Dragons Lair'],
        ['Gaming Goat', 'Gaming Goat']], 
        :include_blank => true %><br><br>
    <%= f.label :day_of_week, 'Which Day?' %>
    <%= f.select :day_of_week, [
        ['Sunday', 'Sunday'], 
        ['Monday', 'Monday'], 
        ['Tuesday', 'Tuesday'],
        ['Wednesday', 'Wednesday'],
        ['Thursday', 'Thursday'],
        ['Friday', 'Friday'],
        ['Saturday', 'Saturday']], 
        include_blank: true %><br><br>

app/views/gatherings/edit.html.erb
<h1>Edit your Gathering</h1>

<%= render partial: 'layouts/errors', locals: {object: @gathering} %>

<%= form_for(@gathering) do |f| %>
    <h2>Edit Gathering for <%=@gathering.group.game_title%></h2>
    <%=f.hidden_field :gathering_group_id, value: @gathering.group.id%>
    <br><br>
    <%= render partial: 'form', locals: {f: f} %><br><br>
    <%= f.submit 'Edit Gathering' %>
<% end %>

app/views/gatherings/index.html.erb
<h1>All the Gatherings</h1>
<ul>
<% @gatherings.each do |g| %>
    <%= link_to g do %>
        <li><%= g.group.game_title %> meets at <%= g.game_cafe %> on <%= g.day_of_week.pluralize %>.</li>
    <% end %>
<% end %>
</ul>

app/views/gatherings/new.html.erb
<h1>Create a New Gathering</h1>

<%= render partial: 'layouts/errors', locals: {object: @gathering} %>

<%= form_for(@gathering) do |f| %>
    <%if @group%>
        <h2>New Gathering for <%= @group.game_title %></h2>
        <%=f.hidden_field :group_id, value: @group.id %>
    <%else%>
        <h3>Select a Group</h3>
        <%= f.label :group_id %>
        <%= f.collection_select :group_id, Group.all, :id, :game_title, include_blank: true %>
    <% end %>
    <br><br>
    <%= render partial: 'form', locals: {f: f} %>
    <%= f.submit 'Create Gathering' %>
<% end %>

app/views/gatherings/show.html.erb
<h1><%= @gathering.group.game_title %></h1>
<h2><%= @gathering.game_cafe %></h2>
<h3><%= @gathering.day_of_week %></h3>
<h4><%= @gathering.gamer.username %></h4>
<%= link_to "Edit this Gathering", edit_group_gathering_path(@gathering.group) %>
<br><br>
<%= button_to "Delete Gathering", gathering_path(@gathering), method: :delete %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <%= f.label :game_title %>
  <%= f.text_field :game_title %>
  <%= f.label :game_category %>
  <%= f.select :game_category, [
      ['Board Game', 'Board Game'], 
      ['Card Game', 'Card Game'], 
      ['RPG', 'RPG']], 
      :include_blank => true %>
  <%= f.submit 'Create Group' %>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit your gaming group</h1>

<%= render partial: 'layouts/errors', locals: {object: @group} %>

<%= render 'form' %>

app/views/groups/index.html.erb
<h1>List of Game Groups</h1>

<%= form_tag('/groups', method: 'get') do %>
    <%= label_tag(:game_category, 'Filter by category') %>
    <%= select_tag(:game_category, 
        "<option>Board Game</option><option>Card Game</option><option>RPG</option>", 
        :include_blank => true) %>
    <%= submit_tag('Filter') %>
<% end %>
<ul>
<% @groups.each do |group| %>
    <li><h3><%= link_to group.game_title, group_path(group) %> - 
    <%= group.game_category %></h3></li>
<% end %>
</ul>

app/views/groups/new.html.erb
<h1>Create a new gaming group</h1>

<%= render partial: 'layouts/errors', locals: {object: @group} %>

<%= render 'form' %>

app/views/groups/show.html.erb
<h1><%= @group.game_title %></h1>
<h2><%= @group.game_category %></h2>
<h3>Gamers already in this group:</h3>
<ul>
<% @group.gamers.each do |group_gamers| %>
    <h4><li><%= group_gamers.username %></li></h4>
<% end %>
</ul>
<%= link_to "Edit Group", edit_group_path(@group) %>
<br><br>
<%= link_to "Create Gathering", new_group_gathering_path(@group) %>
<br><br>
<%= button_to "Delete Group", group_path(@group), method: :delete %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this from being saved:
    </h2>
 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamingGroupGatherings</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if logged_in? %>
    <%= link_to 'My Page', home_path %>
    <%= link_to 'Gatherings', gatherings_path %>
    <%= link_to 'Groups', groups_path %>
    <%= link_to 'Logout', logout_path, method: 'delete' %>
  <% else %>
    <%= link_to 'Home', root_path %>
  <% end %>
  
    <%= yield %>
  </body>
</html>